name: Gradle Build  
  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
      - uses: actions/checkout@v2  
        with:  
          submodules: true # 确保初始化git子模块  
  
      - name: Set up JDK 11  
        uses: actions/setup-java@v2  
        with:  
          java-version: '11'  
          distribution: 'adopt'  
  
      # 如果需要其他环境设置或依赖项，可以在这里添加  
  
      - name: Initialize Git Submodules  
        run: ./gradlew initGitSubmodules  
  
      - name: Setup Upstream  
        run: ./gradlew setupUpstream  
  
      - name: Apply Patches  
        run: ./gradlew applyPatches  
  
      - name: Build with Paperclip  
        run: ./gradlew paperclip  
  
      # 如果你想要将构建产物作为artifact保存，可以添加以下步骤  
      - name: Archive build artifacts  
        uses: actions/upload-artifact@v2  
        with:  
          name: build-artifacts  
          path: |  
            # 这里指定你想要保存的构建产物的路径  
            build/libs/*.jar  
  
      # 如果需要进一步的测试或部署步骤，可以在这里添加
